# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  slack: circleci/slack@4.4.2
jobs:
  publish-docker-image:
    docker:
      - image: cimg/base:stable
        environment:
          PLATFORM: linux/amd64,linux/arm64,linux/arm
          SLACK_DEFAULT_CHANNEL: ${SLACK_CHANNEL_PARQUET_TOOLS}
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.14
      - run:
          name: Build and push to docker hub
          no_output_timeout: 60m
          command: |
            echo "${DOCKER_HUB_TOKEN}" | docker login -u hangxie --password-stdin
            echo "${GITHUB_TOKEN}" | docker login -u baldemort-bot --password-stdin ghcr.io
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create multi-platform
            docker buildx create multi-platform --platform ${PLATFORM} --use
            docker buildx build --progress plain \
                -f Dockerfile --push \
                --platform ${PLATFORM} \
                -t hangxie/hadoop-all-in-one:${CIRCLE_TAG} \
                -t hangxie/hadoop-all-in-one:latest \
                -t ghcr.io/hangxie/hadoop-all-in-one:${CIRCLE_TAG} \
                -t ghcr.io/hangxie/hadoop-all-in-one:latest \
                .
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
      - slack/notify:
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "> tag ${CIRCLE_TAG} pushed to <https://hub.docker.com/r/hangxie/hadoop-all-in-one/tags|hangxie/hadoop-all-in-one> by ${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }

workflows:
  version: 2
  main:
    jobs:
      - publish-docker-image:
          context: default
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
