name: Release Build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve release tag to build
        run: |
          echo "REL_TAG=$(cat ./build/VERSION)" >> ${GITHUB_ENV}
      - name: Log into Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to docker hub and ghcr.io
        env:
          PLATFORM: linux/amd64,linux/arm64
        run: |
            docker context create multi-platform
            docker run --privileged --rm tonistiigi/binfmt --install all
            docker buildx create multi-platform --platform ${{ env.PLATFORM }} --use
            docker buildx build --progress plain \
                -f package/container/Dockerfile --push \
                --platform ${{ env.PLATFORM }} \
                -t hangxie/hadoop-all-in-one:${{ env.REL_TAG }} \
                -t hangxie/hadoop-all-in-one:latest \
                -t ghcr.io/hangxie/hadoop-all-in-one:${{ env.REL_TAG }} \
                -t ghcr.io/hangxie/hadoop-all-in-one:latest \
                .
